import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const outfit = Outfit({ subsets: ['latin'], weight: ['400', '500', '600', '700'] })

export const metadata = {
  title: "Blog Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet' />
      </head>
      <body
        className={`${outfit.className}`}
      >
        <Header />

        {children}
      </body>
    </html>
  );
}
